"""Pytest configuration for performance tests.

All tests in this directory are automatically marked as performance tests.
Run only performance tests with:  pytest -m performance
Exclude performance tests with:   pytest -m "not performance"

Each session writes to its own folder:
  tests/performance/results/{timestamp}_{device}/
    results.json      — benchmark timings and environment
    figs/             — plots generated by the session
    traces/           — XLA/Perfetto traces (PERF_TRACE=1)
"""

from __future__ import annotations

import json
import os

# tests/conftest.py forces JAX_PLATFORMS=cpu to avoid sharding-mesh mismatches
# in unit/integration tests. Performance benchmarks need the real device (GPU),
# so remove that restriction before JAX is first imported in this session.
os.environ.pop("JAX_PLATFORMS", None)
from datetime import datetime, timezone
from pathlib import Path

import pytest

from .utils import BenchmarkResult, capture_env

_RESULTS_DIR = Path(__file__).parent / "results"


def pytest_collection_modifyitems(items):
    for item in items:
        if "performance" in Path(str(item.fspath)).parts:
            item.add_marker(pytest.mark.performance)


@pytest.fixture(scope="session")
def perf_env() -> dict:
    return capture_env()


@pytest.fixture(scope="session")
def perf_run_dir(perf_env) -> Path:
    """Create and return the per-session output folder.

    All session outputs (JSON, figs, traces) land here so the entire
    ``results/`` tree can be gitignored with a single rule.
    """
    ts = datetime.now(timezone.utc).strftime("%Y%m%dT%H%M%SZ")
    devices = perf_env.get("devices", [])
    device_slug = (
        devices[0].get("kind", "cpu").replace(" ", "_").lower()
        if devices else "cpu"
    )
    run_dir = _RESULTS_DIR / f"{ts}_{device_slug}"
    run_dir.mkdir(parents=True, exist_ok=True)
    (run_dir / "figs").mkdir(exist_ok=True)
    (run_dir / "traces").mkdir(exist_ok=True)
    return run_dir


@pytest.fixture(scope="session")
def perf_sink() -> list[BenchmarkResult]:
    """Session-scoped list; tests append BenchmarkResult objects here."""
    return []


def pytest_sessionfinish(session, exitstatus):
    """Write collected benchmark results into the per-run folder."""
    sink: list[BenchmarkResult] = getattr(session, "_perf_sink", None) or []
    run_dir: Path | None = getattr(session, "_perf_run_dir", None)

    if not sink or run_dir is None:
        return

    ts = run_dir.name.split("_")[0]
    env = sink[0].env if sink else {}
    payload = {
        "session_timestamp": ts,
        "env": env,
        "results": [r.to_dict() for r in sink],
    }
    out_path = run_dir / "results.json"
    out_path.write_text(json.dumps(payload, indent=2))
    print(f"\nPerformance results written to {out_path}")


@pytest.fixture(autouse=True)
def _register_sink(request, perf_sink, perf_run_dir):
    """Inject sink and run_dir into the session for pytest_sessionfinish."""
    request.session._perf_sink = perf_sink  # type: ignore[attr-defined]
    request.session._perf_run_dir = perf_run_dir  # type: ignore[attr-defined]
